name: opencv-environment
channels:
    - conda-forge
    - quantstack
dependencies:
    - xeus-cling
    - pip:
        - opencv-contrib-python
        - wheel
        - numpy
        - scipy
        - matplotlib
        - scikit-image
        - scikit-learn
        - dlib
