#!/bin/bash

cwd=$(pwd)

mkdir opencv-installation

git clone https://github.com/opencv/opencv.git
cd opencv
git checkout 3.4
cd ..

git clone https://github.com/opencv/opencv_contrib.git
cd opencv_contrib
git checkout 3.4
cd ..

cd opencv
mkdir build
cd build

cmake -D CMAKE_BUILD_TYPE=RELEASE \
            -D CMAKE_INSTALL_PREFIX=$cwd/opencv-installation \
            -D INSTALL_C_EXAMPLES=ON \
            -D INSTALL_PYTHON_EXAMPLES=ON \
            -D WITH_TBB=ON \
            -D WITH_V4L=ON \
        -D WITH_OPENGL=ON \
        -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules \
        -D BUILD_EXAMPLES=ON ..

make -j$(nproc)
make install

cd $cwd


wget http://dlib.net/files/dlib-19.16.tar.bz2
tar -xvjf dlib-19.16.tar.bz2
cd dlib-19.16
mkdir build
mkdir ../dlib-installation
cd build
cmake -DBUILD_SHARED_LIBS=1 -DCMAKE_INSTALL_PREFIX=$cwd/dlib-installation ..
make
make install

cd $cwd

rm -rf opencv
rm -rf opencv_contrib
rm -rf dlib-19.16
rm -rf dlib-19.16.tar.bz2
